/*
** EPITECH PROJECT, 2024
** Vendetta / Header
** File description:
** iItems
*/

#ifndef ITEMS_H_
    #define ITEMS_H_

    #include "inventory.h"
    #include "my_game.h"


static const item_t ITEMS[] = {
    {
        .name = "aidkit",
        .label = "Aid Kit",
        .sprite_id = SP_AIDKIT,
        .rarity = 0.115523,
        .weight = 0.5,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 10,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "armor",
        .label = "Bulletproof vest (LVL.1)",
        .sprite_id = SP_ARMOR,
        .rarity = 0.022004,
        .weight = 1.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_ARMOR,
        .damage = 0,
        .armor = 7,
        .health = 0,
        .speed = -3,
        .effect = NULL
    },
    {
        .name = "armor2",
        .label = "Bulletproof vest (LVL.2)",
        .sprite_id = SP_ARMOR2,
        .rarity = 0.013189,
        .weight = 2.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_ARMOR,
        .damage = 0,
        .armor = 13,
        .health = 0,
        .speed = -6,
        .effect = NULL
    },
    {
        .name = "armor3",
        .label = "Bulletproof vest (LVL.3)",
        .sprite_id = SP_ARMOR3,
        .rarity = 0.008243,
        .weight = 3.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_ARMOR,
        .damage = 0,
        .armor = 20,
        .health = 0,
        .speed = -8,
        .effect = NULL
    },
    {
        .name = "bandage",
        .label = "Bandage",
        .sprite_id = SP_BANDAGE,
        .rarity = 0.115523,
        .weight = 0.2,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 4,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "bone",
        .label = "Bone",
        .sprite_id = SP_BONE,
        .rarity = 0.115523,
        .weight = 0.3,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "cash",
        .label = "Cash",
        .sprite_id = SP_CASH,
        .rarity = 0.115523,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "ephedrine",
        .label = "Ephedrine",
        .sprite_id = SP_EPHEDRINE,
        .rarity = 0.013189,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "first_book",
        .label = "First Book",
        .sprite_id = SP_FIRST_BOOK,
        .rarity = 0.0,
        .weight = 0.5,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = first_book_callback
    },
    {
        .name = "goldcoin",
        .label = "Gold Coin",
        .sprite_id = SP_GOLDCOIN,
        .rarity = 0.002475,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "heroin",
        .label = "Heroin",
        .sprite_id = SP_HEROIN,
        .rarity = 0.013189,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "joint",
        .label = "Weed Joint",
        .sprite_id = SP_JOINT,
        .rarity = 0.022004,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "keya",
        .label = "Key A",
        .sprite_id = SP_KEYA,
        .rarity = 0.0,
        .weight = 0.2,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "keyb",
        .label = "Key B",
        .sprite_id = SP_KEYB,
        .rarity = 0.0,
        .weight = 0.2,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "keyc",
        .label = "Key C",
        .sprite_id = SP_KEYC,
        .rarity = 0.0,
        .weight = 0.2,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "knife",
        .label = "Knife",
        .sprite_id = SP_KNIFE,
        .rarity = 0.013189,
        .weight = 0.5,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_WEAPON,
        .damage = 5,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "lighter",
        .label = "Lighter",
        .sprite_id = SP_LIGHTER_BLUE,
        .rarity = 0.2,
        .weight = 0.115523,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "mask1",
        .label = "Demon Mask",
        .sprite_id = SP_MASK1,
        .rarity = 0.008243,
        .weight = 0.5,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_HELMET,
        .damage = 0,
        .armor = 5,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "mask2",
        .label = "Horse Mask",
        .sprite_id = SP_MASK2,
        .rarity = 0.002475,
        .weight = 0.5,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_HELMET,
        .damage = 0,
        .armor = 9,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "mask3",
        .label = "Bike Helmet",
        .sprite_id = SP_MASK3,
        .rarity = 0.013189,
        .weight = 1.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_HELMET,
        .damage = 0,
        .armor = 3,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "mask4",
        .label = "Bandana",
        .sprite_id = SP_MASK4,
        .rarity = 0.022004,
        .weight = 0.1,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_HELMET,
        .damage = 0,
        .armor = 1,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "rifle",
        .label = "Mk.18 Mod 0",
        .sprite_id = SP_MK18,
        .rarity = 0.002475,
        .weight = 3.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_WEAPON,
        .damage = 17,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "oldpaper",
        .label = "Old Paper",
        .sprite_id = SP_OLD_PAPER,
        .rarity = 0.115523,
        .weight = 0.1,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "oxycodone",
        .label = "Oxycodone",
        .sprite_id = SP_OXY,
        .rarity = 0.022004,
        .weight = 0.2,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "pistol",
        .label = "Pistol",
        .sprite_id = SP_PISTOLMK2,
        .rarity = 0.008243,
        .weight = 1.5,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_WEAPON,
        .damage = 11,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "shotgun",
        .label = "Shotgun",
        .sprite_id = SP_PUMPSHOTGUN,
        .rarity = 0.002475,
        .weight = 4.0,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_WEAPON,
        .damage = 23,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "ring",
        .label = "Ring",
        .sprite_id = SP_RING,
        .rarity = 0.022004,
        .weight = 0.3,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "rolex",
        .label = "Rolex",
        .sprite_id = SP_ROLEX,
        .rarity = 0.022004,
        .weight = 0.8,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = false,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    },
    {
        .name = "second_book",
        .label = "Second Book",
        .sprite_id = SP_SECOND_BOOK,
        .rarity = 0.0,
        .weight = 0.5,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = second_book_callback
    },
    {
        .name = "shoes",
        .label = "Shoes",
        .sprite_id = SP_SHOES,
        .rarity = 0.008243,
        .weight = 0.3,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_SHOES,
        .damage = 0,
        .armor = 2,
        .health = 0,
        .speed = 10,
        .effect = NULL
    },
    {
        .name = "blue_shoes",
        .label = "Blue Shoes",
        .sprite_id = SP_SHOES_BLUE,
        .rarity = 0.022004,
        .weight = 0.2,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_SHOES,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 6,
        .effect = NULL
    },
    {
        .name = "green_shoes",
        .label = "Green Shoes",
        .sprite_id = SP_SHOES_GREEN,
        .rarity = 0.0,
        .weight = 0.2,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_SHOES,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 3,
        .effect = NULL
    },
    {
        .name = "red_shoes",
        .label = "Red Shoes",
        .sprite_id = SP_SHOES_BLUE,
        .rarity = 0.022004,
        .weight = 0.2,
        .is_stackable = false,
        .is_equipable = true,
        .is_usable = false,
        .type = ITEM_SHOES,
        .damage = 0,
        .armor = 3,
        .health = 0,
        .speed = 3,
        .effect = NULL
    },
    {
        .name = "third_book",
        .label = "Third Book",
        .sprite_id = SP_THIRD_BOOK,
        .rarity = 0.0,
        .weight = 0.5,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = third_book_callback
    },
    {
        .name = "whiskey",
        .label = "Whiskey",
        .sprite_id = SP_WHISKEY,
        .rarity = 0.022004,
        .weight = 1.0,
        .is_stackable = true,
        .is_equipable = false,
        .is_usable = true,
        .type = ITEM_MISC,
        .damage = 0,
        .armor = 0,
        .health = 0,
        .speed = 0,
        .effect = NULL
    }
};

    #define ITEM_COUNT sizeof(ITEMS) / sizeof(item_t)

#endif /* !ITEMS_H_ */
